In [ ]:
# Task 1: Data Preprocessing for
# Machine Learning
# Description: Preprocess a raw dataset to make it ready for machine learning.

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from  sklearn.model_selection import  train_test_split
from sklearn.preprocessing import MinMaxScaler

In [ ]:
iris = pd.read_csv("C:/Users/adelu/OneDrive/Documents/codveda ineintership projects/task1/iris.csv")

iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
iris.head(100)

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

[100 rows x 5 columns]

In [ ]:
# check for  missing  data
iris.sum().isna()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool

In [ ]:
#  label  encording for species

le = LabelEncoder()

iris["species"] = le.fit_transform(iris["species"])
iris

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [ ]:
# normaliztion and  feature spliting 

X = iris.drop("species", axis=1)
y = iris["species"]

# normalize features
scaler = MinMaxScaler()

X_normalized = scaler.fit_transform(X)

# convert back to dataframe
x = pd.DataFrame(X_normalized, columns=X.columns)

print(x.head())

   sepal_length  sepal_width  petal_length  petal_width
0      0.222222     0.625000      0.067797     0.041667
1      0.166667     0.416667      0.067797     0.041667
2      0.111111     0.500000      0.050847     0.041667
3      0.083333     0.458333      0.084746     0.041667
4      0.194444     0.666667      0.067797     0.041667

In [ ]:
# training and testing sets

x_train,x_test,y_train,y_test = train_test_split(x,y , test_size=0.2  )